spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE


  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888/

server:
  port: 9999


